#include "scene/beach_element.hpp"

namespace moana {

BeachElement::BeachElement()
{
    const std::string moanaRoot = MOANA_ROOT;

    m_baseObj = moanaRoot + "/island/obj/isBeach/isBeach.obj";

    m_objPaths = {
        moanaRoot + "/island/obj/isBeach/archives/xgFibers_archiveseedpodb_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgFibers_archivepineneedle0003_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgFibers_archivepineneedle0002_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgFibers_archivepineneedle0001_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0006_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0007_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0002_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0003_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0004_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0005_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0008_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgHibiscus_archiveHibiscusFlower0009_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgStones_archiveRock0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShells_archiveShell0008_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgSeaweed_archiveSeaweed0063_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgSeaweed_archiveSeaweed0064_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgSeaweed_archiveSeaweed0001_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgSeaweed_archiveSeaweed0065_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgSeaweed_archiveSeaweed0003_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgSeaweed_archiveSeaweed0002_mod.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0009_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0008_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveCoral0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPebbles_archiveRock0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0008_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgShellsSmall_archiveShell0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPalmDebris_archiveLeaflet0127_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPalmDebris_archiveLeaflet0125_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPalmDebris_archiveLeaflet0126_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPalmDebris_archiveLeaflet0123_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgPalmDebris_archiveLeaflet0124_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0008_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0009_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0008_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0007_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveCoral0003_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0001_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveShell0002_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0004_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0006_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0005_geo.obj",
        moanaRoot + "/island/obj/isBeach/archives/xgGroundCover_archiveRock0003_geo.obj",
    };

    m_binPaths = {
        "../scene/isBeach-xgFibers_archiveseedpodb_mod.bin",
        "../scene/isBeach-xgFibers_archivepineneedle0003_mod.bin",
        "../scene/isBeach-xgFibers_archivepineneedle0002_mod.bin",
        "../scene/isBeach-xgFibers_archivepineneedle0001_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0006_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0007_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0002_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0003_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0004_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0005_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0008_mod.bin",
        "../scene/isBeach-xgHibiscus_archiveHibiscusFlower0009_mod.bin",
        "../scene/isBeach-xgStones_archiveRock0001_geo.bin",
        "../scene/isBeach-xgStones_archiveRock0004_geo.bin",
        "../scene/isBeach-xgStones_archiveRock0006_geo.bin",
        "../scene/isBeach-xgStones_archiveRock0005_geo.bin",
        "../scene/isBeach-xgStones_archiveRock0007_geo.bin",
        "../scene/isBeach-xgStones_archiveRock0003_geo.bin",
        "../scene/isBeach-xgStones_archiveRock0002_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0003_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0001_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0007_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0006_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0004_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0002_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0005_geo.bin",
        "../scene/isBeach-xgShells_archiveShell0008_geo.bin",
        "../scene/isBeach-xgSeaweed_archiveSeaweed0063_geo.bin",
        "../scene/isBeach-xgSeaweed_archiveSeaweed0064_geo.bin",
        "../scene/isBeach-xgSeaweed_archiveSeaweed0001_mod.bin",
        "../scene/isBeach-xgSeaweed_archiveSeaweed0065_geo.bin",
        "../scene/isBeach-xgSeaweed_archiveSeaweed0003_mod.bin",
        "../scene/isBeach-xgSeaweed_archiveSeaweed0002_mod.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0002_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0003_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0004_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0001_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0002_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0004_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0009_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0005_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0007_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0006_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0007_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0008_geo.bin",
        "../scene/isBeach-xgPebbles_archiveCoral0005_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0001_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0003_geo.bin",
        "../scene/isBeach-xgPebbles_archiveRock0006_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0004_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0002_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0008_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0001_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0006_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0003_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0005_geo.bin",
        "../scene/isBeach-xgShellsSmall_archiveShell0007_geo.bin",
        "../scene/isBeach-xgPalmDebris_archiveLeaflet0127_geo.bin",
        "../scene/isBeach-xgPalmDebris_archiveLeaflet0125_geo.bin",
        "../scene/isBeach-xgPalmDebris_archiveLeaflet0126_geo.bin",
        "../scene/isBeach-xgPalmDebris_archiveLeaflet0123_geo.bin",
        "../scene/isBeach-xgPalmDebris_archiveLeaflet0124_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0002_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0004_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0004_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0006_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0002_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0001_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0007_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0001_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0003_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0006_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0008_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0009_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0007_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0005_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0008_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0007_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveCoral0003_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0001_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0005_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveShell0002_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0004_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0006_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0005_geo.bin",
        "../scene/isBeach-xgGroundCover_archiveRock0003_geo.bin",
    };

    m_hasElementInstances = true;
    m_elementInstancesBinPath = "../scene/isBeach-root.bin";
}

}
