#include "scene/palm_rig_element.hpp"

namespace moana {

PalmRigElement::PalmRigElement()
{
    const std::string moanaRoot = MOANA_ROOT;

    m_elementName = "isPalmRig";

    m_baseObjs = {
        moanaRoot + "/island/obj/isPalmRig/isPalmRig.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig18.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig19.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig16.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig17.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig14.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig15.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig12.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig13.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig10.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig11.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig30.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig31.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig32.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig33.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig8.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig9.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig4.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig5.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig6.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig7.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig2.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig3.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig27.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig26.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig25.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig24.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig23.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig22.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig21.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig20.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig29.obj",
        moanaRoot + "/island/obj/isPalmRig/isPalmRig28.obj",
    };

    m_objArchivePaths = {

    };

    m_elementInstancesBinPaths = {
        "../scene/isPalmRig.bin",
        "../scene/isPalmRig18.bin",
        "../scene/isPalmRig19.bin",
        "../scene/isPalmRig16.bin",
        "../scene/isPalmRig17.bin",
        "../scene/isPalmRig14.bin",
        "../scene/isPalmRig15.bin",
        "../scene/isPalmRig12.bin",
        "../scene/isPalmRig13.bin",
        "../scene/isPalmRig10.bin",
        "../scene/isPalmRig11.bin",
        "../scene/isPalmRig30.bin",
        "../scene/isPalmRig31.bin",
        "../scene/isPalmRig32.bin",
        "../scene/isPalmRig33.bin",
        "../scene/isPalmRig8.bin",
        "../scene/isPalmRig9.bin",
        "../scene/isPalmRig4.bin",
        "../scene/isPalmRig5.bin",
        "../scene/isPalmRig6.bin",
        "../scene/isPalmRig7.bin",
        "../scene/isPalmRig2.bin",
        "../scene/isPalmRig3.bin",
        "../scene/isPalmRig27.bin",
        "../scene/isPalmRig26.bin",
        "../scene/isPalmRig25.bin",
        "../scene/isPalmRig24.bin",
        "../scene/isPalmRig23.bin",
        "../scene/isPalmRig22.bin",
        "../scene/isPalmRig21.bin",
        "../scene/isPalmRig20.bin",
        "../scene/isPalmRig29.bin",
        "../scene/isPalmRig28.bin",
    };

    m_primitiveInstancesBinPaths = {
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    };

    m_primitiveInstancesHandleIndices = {
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    };

    }

}
